### ISSUE TITLE
Diego Ernesto mapa mental

### ISSUE THREAD

**Issue by DiegoLV117** [SistemasTecTlaxiaco/actividad-4-mapa-mental-DiegoLV117#2]
[https://drive.google.com/drive/folders/1Peu7WHzhVZhZZoE5gdaTqLkqxVceUaCB](url)
lo subi a mi drive porque la pagina no me deja subir el archivo html y en png se ve borroso 
(Copiar el link y pegar en la barra del navegador para ver y descargar)

**Comment by 00Asaf00** [comment]
- Manejo: 20%
- Relaciones: 25%
- Calidad: 25%
- Jerarquía: 20%

Calificación:
(90%)/100*20 = 18/20

Comentarios:

- El modo en el que se subió el archivo complica un poco la visualización, favor de corregirlo cuando sea posible.

- La calidad es buena, pero favor de usar un mejor manejo a la hora de diseñar el documento.


Evaluado por el Equipo de Edgar Iván

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
